name: angelikasawicka-pl
region: fra
domains:
  - domain: angelikasawicka.pl
    type: PRIMARY
static_sites:
  - name: web
    github:
      repo: mikolajlehman/angelikasawicka.pl
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    routes:
      - path: /
